#!/system/xbin/bash
clear
echo "YouTube : "E n z o m e s"
"PUBG MOBILE SEASON 11 BAN ГАРГАХ SCRIPT"
echo " USER ID : " 085779515200"
" Enzomes Hacking Tencent :) Та PUBG MOBILE ийнхаа ID ийг бич нүү"
sleep 1
echo "Одоо бичэх"
echo ""
echo "\033[33;1m=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*"
echo "hacked"

echo ="ID Бичэх Та PUBG MOBILE Бан Гаргах бол"
read p;
sleep 1
sleep 2
sleep 3
echo ="Хүлээн Авч байна та түр хүлээн үү";
read p;
sleep 1
echo ="Tencent Hacking 12%"
read p;
sleep 1
sleep 2
echo ="cd/sdcard/Android/obb/com.tencent.ig/main.11460.com.tencent.ig.obb/kickweb/attack.sh.on.slawabulestock"
read p;
sleep 1
echo "tencent hacking 23%" 
sleep 1
sleep 2
sleep 3
echo "tencent hacking 33%"
sleep 1
sleep 2
sleep 3
echo "attacking hacking 44%"
sleep 1
sleep 2
sleep 3
echo "reset.sh.on/main.11460.com.tencent.ig.obb"
sleep 1
sleep 2
sleep 3
echo ="attack succesfull 100% hacked by enzomes mongolian hacker thanks :)"
sleep 1
sleep 2
echo ="Thanks Subscribe My YouTube Channel name : [ E n z o m e s ]"
read p;
sleep 1
echo "100"
